In my project, I am going to translate what I learned about anyonic chains in the simpler case of Fibonacci anyons into computer language. This means that I will need first of all to construct the Hilbert Space of all possible chains, with the ability to input the length and boundary conditions of the problem. 

First of all, we build a Hilbert space of set length, making it small enough that we are able to check its validity by eye and be confident that we are on the right path. Let's write a program to give us all possible anyonic chains of length n = 5: the idea here is to have all possible lists of length 5 which can contain only zeroes and ones as elements and where a zero does not appear more than once in a row.  

In [1]:
import numpy as np
import scipy.linalg as la

Chains_1 = [[0],[1]] 

#We create a list containing only the elements zero and one. 
#This is the Hilbert space of anyonic chains of length 1.

Chains = Chains_1.copy()

output = []

for j in range(4):
#We want to execute this next loop 5 times, as the idea is starting from the space of length 1 chains and making the lists it
#contains longer by 1 element to create the space of chains of length 2. Each list can give birth to one or two lists
#in the new space based on the anyon fusion rules.  
    for i in Chains: 
#In each step of this loop, we take an element of our list of lists and check the last element that appears in it. 
#If it's a one, the next element can be either a one or a zero. 
#If it's a zero, the next element can only be a one. 
#Thus, we create one or two placeholder lists which will be a copy of the mother list and add zeroes or ones in order
#to create the new elements we are looking for. 
#We need to copy lists and not just set them equal to each other, otherwise the paceholder list would just become a poiner
#to the same initial list, which we don't want to modify. 
        if i[-1] == 1:
            chain0 = []
            chain1 = []
            chain0 = i.copy()
            chain0.append(0)
            chain1 = i.copy()
            chain1.append(1)
            output.append(chain0)
            output.append(chain1)
        else:
            chain1 = []
            chain1 = i.copy()
            chain1.append(1)
            output.append(chain1)
#Once we have our one or two new placeholder chains, we append them to a placeholder output list. 
    Chains = output.copy()
#Once we have gone through all the elements of the previous Hilbert space, we copy the placeholder list into the list
#we are cycling through and start the cycle all over again to obtain a higher dimension space. 
    output.clear()

#Once we are done, we print each element of our Hilbert space on a separate line to make visualisation more pleasant.
for i in Chains:
    print(i)        

[0, 1, 0, 1, 0]
[0, 1, 0, 1, 1]
[0, 1, 1, 0, 1]
[0, 1, 1, 1, 0]
[0, 1, 1, 1, 1]
[1, 0, 1, 0, 1]
[1, 0, 1, 1, 0]
[1, 0, 1, 1, 1]
[1, 1, 0, 1, 0]
[1, 1, 0, 1, 1]
[1, 1, 1, 0, 1]
[1, 1, 1, 1, 0]
[1, 1, 1, 1, 1]


We can also add one more line to check how the dimension of the space evolves with its length growing. This is what gives the name to the anyons, since the growing dimensions create a Fibonacci sequence.  

In [2]:
Chains_1 = [[0],[1]] 

Chains = Chains_1.copy()

output = []

print(f"The dimension of the Hilbert space of dimension n = 1 is {len(Chains)}")

for j in range(4):
    for i in Chains: 
        if i[-1] == 1:
            chain0 = []
            chain1 = []
            chain0 = i.copy()
            chain0.append(0)
            chain1 = i.copy()
            chain1.append(1)
            output.append(chain0)
            output.append(chain1)
        else:
            chain1 = []
            chain1 = i.copy()
            chain1.append(1)
            output.append(chain1)
    Chains = output.copy()
    output.clear()
    print(f"The dimension of the Hilbert space of dimension n = {j+2} is {len(Chains)}")

The dimension of the Hilbert space of dimension n = 1 is 2
The dimension of the Hilbert space of dimension n = 2 is 3
The dimension of the Hilbert space of dimension n = 3 is 5
The dimension of the Hilbert space of dimension n = 4 is 8
The dimension of the Hilbert space of dimension n = 5 is 13


And now let's do the same for a generic length n: the program will be the same and instead of n = 5 we will just have n taken from the console input. 

In [3]:
n = int(input("Please specify length n: "))

Please specify length n: 3


In [4]:
def Chains(n):
    import numpy as np
    Chains = [[0],[1]]

    output = []

    for j in range(n - 1):
        for i in Chains: 
            if i[-1] == 1:
                chain0 = []
                chain1 = []
                chain0 = i.copy()
                chain0.append(0)
                chain1 = i.copy()
                chain1.append(1)
                output.append(chain0)
                output.append(chain1)
            else:
                chain1 = []
                chain1 = i.copy()
                chain1.append(1)
                output.append(chain1)
        Chains = output.copy()
        output.clear()
    return np.array(Chains)

In [5]:
print(Chains(n))

[[0 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


And once again let's see how the dimensions evolve:

In [6]:
Chains_1 = np.array([[0],[1]])

print(f"The dimension of the Hilbert space of dimension n = 1 is {len(Chains_1)}")

for j in range(n - 1):
    print(f"The dimension of the Hilbert space of dimension n = {j+2} is {len(Chains(j+2))}")

The dimension of the Hilbert space of dimension n = 1 is 2
The dimension of the Hilbert space of dimension n = 2 is 3
The dimension of the Hilbert space of dimension n = 3 is 5


These numbers indeed reproduce a Fibonacci sequence. 

An additional level of complexity comes from adding the possibility of setting boundary conditions for the chains (with the ability to make them periodic or not, in particular). We can do this by first asking for boundary conditions as an input and storing the two numbers as variables:

In [7]:
Boundary = input("Please set boundary conditions in the form X, X:")

a = int(Boundary[0]) 
b = int(Boundary[-1])

a = 0
b = 0

if a != 0 and a!= 1: 
    print("Error: the left boundary is not valid.")
if b != 0 and b!= 1: 
    print("Error: the right boundary is not valid.")

Please set boundary conditions in the form X, X:0, 0


And then filtering the chains we obtained before using these parameters:

In [8]:
def Periodic_Chains(n):
    PC = []
    C = Chains(n+1)
    for i in C: 
        if i[0] == i[-1]:
            PC.append(np.delete(i, -1))
    return np.array(PC)

In [9]:
print(Periodic_Chains(3))

[[0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


What we are aiming for now is to associate to each element in the Hilbert Space we constructed an Energy, so that we may construct an Hamiltonian. Following the paper$^{[1]}$ we build it starting from the F-matrix and the projection matrix onto the ground state. We'll be starting with the simple case of fusing three anyons and use the pentagon equation.

$$(F^{\tau \tau c}_\tau)^d_a (F^{a \tau \tau}_\tau)^c_b = (F^{\tau \tau \tau}_d)^c_e (F^{\tau e \tau}_\tau)^d_b (F^{\tau \tau \tau}_b)^e_a$$

This is particularly simple in the case of Fibonacci anyons as since we only have one element in addition to the identity, only fusions of non-trivial elements give interesting results and so the only equation we need to solve is:

$$(F^{\tau \tau \tau}_\tau)^d_a (F^{a \tau \tau}_\tau)^\tau_b = (F^{\tau \tau \tau}_d)^\tau_e (F^{\tau e \tau}_\tau)^d_b (F^{\tau \tau \tau}_b)^e_a$$

To which we also have to add the unitarity constraint: 

$$(F^{\tau \tau \tau}_\tau)^{\dagger} = (F^{\tau \tau \tau}_\tau)^{-1}$$

We will also be using the Yang-Lee version and not the Fibonacci version, so no unitarity, because it will lead to a simpler conformal field theory.

In [10]:
def Null(m):
    
    Null = []

    Null_Row = []

    for i in range(m):
        Null_Row.append(0)
    for i in range (m):
        Null.append(Null_Row.copy())
    return np.array(Null)

print(Null(3))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [11]:
import cmath

r = (5**0.5 + 1)/2

F_YM = np.array([[-r, -1j*r**(-0.5)],[- 1j * r**(0.5), r]]) 

print(F_YM)

[[-1.61803399+0.j          0.        -0.78615138j]
 [ 0.        -1.27201965j  1.61803399+0.j        ]]


Now to get the Hamiltonian we will need to build fusion matrices for pairs on anyons and ,since potentials are defined as differences and not as absolute values, we can make a choice of ground state and attribute to it an arbitrary energy, which for semplicity is chosen as E = -1. To understand the mechanism and be able to automate it, we start from applying it to simple cases. 

Let's start from the case of chains of length n = 2. The space will be given by:

In [12]:
print(Periodic_Chains(2))

[[0 1]
 [1 0]
 [1 1]]


If we choose the state $[1, x]$ in the fusion basis to be our ground state, then we have that the projection matrix onto the ground state will be:  

In [13]:
P_2 = np.zeros((3, 3))

P_2[2][2] = -1

print(P_2)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0. -1.]]


And the fusion matrices in this case will be: 

In [14]:
F_2_1 = np.array([[F_YM[0,0], 0, F_YM[0,1]], [0, 1, 0], [F_YM[1,0], 0, F_YM[1,1]]])

print("F_1")

print(np.around(F_2_1, 3))

print("F_2")

F_2_2 = np.array([[0, F_YM[0,0], F_YM[0,1]],[1, 0, 0],[0, F_YM[1,0], F_YM[1,1]]])

print(np.around(F_2_2, 3))

F_1
[[-1.618+0.j     0.   +0.j     0.   -0.786j]
 [ 0.   +0.j     1.   +0.j     0.   +0.j   ]
 [ 0.   -1.272j  0.   +0.j     1.618+0.j   ]]
F_2
[[ 0.   +0.j    -1.618+0.j     0.   -0.786j]
 [ 1.   +0.j     0.   +0.j     0.   +0.j   ]
 [ 0.   +0.j     0.   -1.272j  1.618+0.j   ]]


From these we can then calculate the local Hamiltonians and then add them to get a global Hamiltonian:

In [15]:
H_12 = la.inv(F_2_1) @ P_2 @ F_2_1

print("H_12")

print(np.around(H_12, 3))

H_21 = la.inv(F_2_2) @ P_2 @ F_2_2

print("H_21")

print(np.around(H_21, 3))

print("H")

H = np.around(H_12 + H_21, 3)

print(H)

H_12
[[ 0.618+0.j     0.   +0.j     0.   +0.786j]
 [ 0.   +0.j     0.   +0.j     0.   +0.j   ]
 [ 0.   +1.272j  0.   +0.j    -1.618+0.j   ]]
H_21
[[ 0.   +0.j     0.   +0.j     0.   +0.j   ]
 [ 0.   +0.j     0.618+0.j     0.   +0.786j]
 [ 0.   +0.j     0.   +1.272j -1.618+0.j   ]]
H
[[ 0.618+0.j     0.   +0.j     0.   +0.786j]
 [ 0.   +0.j     0.618+0.j     0.   +0.786j]
 [ 0.   +1.272j  0.   +1.272j -3.236+0.j   ]]


And then check that its eigenvalues:

In [16]:
import collections
from collections import Counter

eigvals, eigvecs = la.eig(H)

print("The Eigenvalues of H are:")
print(np.around(eigvals, 3))

print("The Eigenvectors of H are:")
print(np.around(eigvecs, 3))

The Eigenvalues of H are:
[-2.618+0.j  0.   +0.j  0.618+0.j]
The Eigenvectors of H are:
[[ 0.   -0.23j   0.618+0.j     0.707+0.j   ]
 [ 0.   -0.23j   0.618+0.j    -0.707+0.j   ]
 [ 0.946+0.j    -0.   +0.486j  0.   +0.j   ]]


Can be fitted to the first exponents of the character series:

In [17]:
eigvals = np.sort(eigvals)
X = np.array([eigvals[0], eigvals[1]])
X = np.around(X,3)
s = np.around(la.solve(np.array([[X[0], 1],[X[1], 1]]), np.array([-2/5,0])),3)

c = Counter(np.around(eigvals*s[0] +s[1],3))

for i in c:
    print (f"{i}, appearing {c[i]} times")

-0.401, appearing 1 times
0.0, appearing 1 times
0.095, appearing 1 times


Which is indeed the case. Let's now take the case of generic n, which I will take equal to 3 to show results:

In [18]:
print(Periodic_Chains(3))

[[0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


The Fusion matrices will be calculated using:

In [19]:
def RRotation(Space1):
    import collections
    Space2 = []
    for a in Space1:
        b = collections.deque(a)
        b.rotate(-1)
        Space2.append(list(b))
    return Space2

def LRotation(Space1):
    import collections
    Space2 = []
    for a in Space1:
        b = collections.deque(a)
        b.rotate(+1)
        Space2.append(list(b))
    return Space2

In [20]:
def Comp_Chains(n, k):
    a = []
    c = Chains(n - 1)
    for j in range(k):
        c = RRotation(c).copy()
    for i in c: 
        if i[0] != i[-1]:
            a.append(np.append(1, i))
        else: 
            a.append(np.append(0, i))
            if i[0] == 1:
                a.append(np.append(1, i))
    for i in range(k):
        a = LRotation(a).copy()
    return np.array(a)

In [21]:
def Reorder(Space1, Space2):
    c = []
    spec = 3000
    for i, a in enumerate(Space1):
        p = 0
        for j, b in enumerate(Space2):
            if np.array_equal(a, b): 
                c.insert(i, a)
                p = 1
        if p == 0:
            spec = i
    if spec != 3000:        
        for j, b in enumerate(Space2):
            p = 0
            for i, a in enumerate(Space1):
                if np.array_equal(a, b):
                    p = 1
            if p == 0:
                c.insert(spec, b)
    return np.array(c)

In [22]:
def Fusion (n):
    Space2 = Chains(n-1)
    import collections 
    Space1 = Periodic_Chains(n)
    H = np.zeros((len(Space1), len(Space1))).astype(complex)
    for i in range(n):
        F = np.zeros((len(Space1), len(Space1))).astype(complex)
        P = np.zeros((len(Space1), len(Space1))).astype(complex)
        Space3 = []
        for a_1 in Periodic_Chains(n):
            a_2 = collections.deque(a_1)
            a_2.rotate(-i)
            Space3.append(list(a_2))
        Space3 = np.array(Space3)
        Space4 = Reorder(Periodic_Chains(n), Comp_Chains(n,i))
        for c in Space2:
            Space1 = Periodic_Chains(n)
            if c[0] != c[-1]:        
                for k, d in enumerate(Space3):
                    if np.array_equal(c, np.delete(d, 0)):
                        Space1[k,i] = 1
                        for g_ind, g in enumerate(Space4):
                            if np.array_equal(Space1[k], g):
                                F[k, g_ind] = 1
                                P[g_ind, g_ind] = -1
            elif c[0] == 1 and c[-1] == 1:
                for k, d in enumerate(Space3):
                    if np.array_equal(c, np.delete(d, 0)):
                        Space1[k, i] = 0
                        for g_ind, g in enumerate(Space4):
                            if np.array_equal(Space1[k], g):
                                F[k, g_ind] = F_YM[d[0], 0]
                        Space1[k, i] = 1
                        for g_ind, g in enumerate(Space4):
                            if np.array_equal(Space1[k], g):
                                F[k, g_ind] = F_YM[d[0], 1]
                                P[g_ind, g_ind] = -1
            elif c[0] == 0 and c[-1] == 0:
                for k, d in enumerate(Space3):
                    if np.array_equal(c, np.delete(d, 0)):
                        Space1[k, i] = 0
                        for g_ind, g in enumerate(Space4):
                            if np.array_equal(Space1[k], g):
                                F[k, g_ind] = 1
        print(F)
        H += la.inv(F) @ P @ F
    return H

And if run with n = 3 we obtain as Hamiltonian, Eigenvalues and Eigenvectors:

In [23]:
H = Fusion(3)

eigvals, eigvecs = la.eig(H)

print("The Hamiltonian H is:")
print(np.around(H,3))

print("The Eigenvalues of H are:")
print(np.around(np.sort(eigvals), 3))

print("The Eigenvectors of H are:")
print(np.around(eigvecs, 3))

[[-1.61803399+0.j          0.        +0.j          0.        +0.j
   0.        -0.78615138j]
 [ 0.        +0.j          1.        +0.j          0.        +0.j
   0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          1.        +0.j
   0.        +0.j        ]
 [ 0.        -1.27201965j  0.        +0.j          0.        +0.j
   1.61803399+0.j        ]]
[[ 1.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [ 0.        +0.j         -1.61803399+0.j          0.        +0.j
   0.        -0.78615138j]
 [ 0.        +0.j          0.        +0.j          1.        +0.j
   0.        +0.j        ]
 [ 0.        +0.j          0.        -1.27201965j  0.        +0.j
   1.61803399+0.j        ]]
[[ 1.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [ 0.        +0.j          1.        +0.j          0.        +0.j
   0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j         -1.61803399+0.j
  

Which, after being fitted, give:

In [24]:
eigvals = np.sort(eigvals)
X = np.array([eigvals[0], eigvals[1]])
X = np.around(X,3)
s = np.around(la.solve(np.array([[X[0], 1],[X[1], 1]]), np.array([-2/5,0])),3)
print(f"Among our fitted eigenvalues there are:")

c = Counter(np.around(eigvals*s[0] +s[1],3))

for i in c:
    print (f"{i}, appearing {c[i]} times")

Among our fitted eigenvalues there are:
-0.4, appearing 1 times
0.0, appearing 1 times
2.743, appearing 2 times


Which end up coinciding with the first exponents of the series.